# Numpy III

In [2]:
import numpy as np
import pandas as pd

1. Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales.

In [3]:
array = np.round(np.random.rand(2,3,5), 1)
array

array([[[0.5, 0.3, 0.7, 0.6, 0.8],
        [0.8, 0.9, 0.6, 0.9, 0.2],
        [0.2, 0.3, 0.6, 0.1, 0.3]],

       [[0.6, 1. , 0.4, 1. , 0.7],
        [0.8, 0.2, 0.6, 0.7, 0.5],
        [0.9, 0.3, 0.8, 0. , 1. ]]])

2. Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

In [4]:
media_arr = np.round(np.mean(array), 1)
media_arr

0.6

3. Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [5]:
max_arr = np.round(np.max(array),1)
max_arr

1.0

4. Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [6]:
min_arr = np.round(np.min(array),1)
min_arr

0.0

5. Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.

In [7]:
arr_vacio = np.empty((2,3,5), dtype = str)
arr_vacio

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

💡 Pista 💡 Tendréis que iterar por el array y cambiar los valores de la matriz vacía. Para eso tendremos que usar distintos condicionales.

- Si el valor del array es igual que la media, se reemplaza por "A"

- Si el valor del array es mayor que la media, se reemplaza por "B".

- Si el valor del array es menor que la media, se reemplaza por "C".

- Si el valor es igual que el máximo, se reemplaza por "D".

- Si el valor es igual que el mínimo, se reemplaza por "E".


In [8]:
array.shape

(2, 3, 5)

In [15]:
# primero necesitamos iterar hasta llegar a los valores

for m in range(array.shape[0]):
    for f in range(array.shape[1]):
        for c in range(array.shape[2]):
            if array[m][f][c] == media_arr:
                arr_vacio[m][f][c] = 'A'
            elif array[m][f][c] > media_arr:
                arr_vacio[m][f][c] = 'B'
            elif array[m][f][c] < media_arr:
                arr_vacio[m][f][c] = 'C'
            elif array[m][f][c] == max_arr:
                arr_vacio[m][f][c] = 'D'
            elif array[m][f][c] == min_arr:
                arr_vacio[m][f][c] = 'E'           
                

In [16]:
arr_vacio

array([[['C', 'C', 'B', 'A', 'B'],
        ['B', 'B', 'A', 'B', 'C'],
        ['C', 'C', 'A', 'C', 'C']],

       [['A', 'B', 'C', 'B', 'B'],
        ['B', 'C', 'A', 'B', 'C'],
        ['B', 'C', 'B', 'C', 'B']]], dtype='<U1')

6. Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.
En este caso:

In [33]:
vacio2 = np.empty((30), dtype = int)
vacio2

array([4602678819172646912, 4599075939470750515, 4604480259023595110,
       4603579539098121011, 4605380978949069210, 4605380978949069210,
       4606281698874543309, 4603579539098121011, 4606281698874543309,
       4596373779694328218, 4596373779694328218, 4599075939470750515,
       4603579539098121011, 4591870180066957722, 4599075939470750515,
       4603579539098121011, 4607182418800017408, 4600877379321698714,
       4607182418800017408, 4604480259023595110, 4605380978949069210,
       4596373779694328218, 4603579539098121011, 4604480259023595110,
       4602678819172646912, 4606281698874543309, 4599075939470750515,
       4605380978949069210,                   0, 4607182418800017408])

- Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1

In [18]:
vacio1 = arr_vacio.copy()
vacio1

array([[['C', 'C', 'B', 'A', 'B'],
        ['B', 'B', 'A', 'B', 'C'],
        ['C', 'C', 'A', 'C', 'C']],

       [['A', 'B', 'C', 'B', 'B'],
        ['B', 'C', 'A', 'B', 'C'],
        ['B', 'C', 'B', 'C', 'B']]], dtype='<U1')

In [47]:
vacio3= vacio1.reshape(30)

- Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2

- Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.

In [41]:
vacio2.size

30

In [45]:
vacio1

array([[['C', 'C', 'B', 'A', 'B'],
        ['B', 'B', 'A', 'B', 'C'],
        ['C', 'C', 'A', 'C', 'C']],

       [['A', 'B', 'C', 'B', 'B'],
        ['B', 'C', 'A', 'B', 'C'],
        ['B', 'C', 'B', 'C', 'B']]], dtype='<U1')

In [48]:
for i in range(vacio2.shape[0]):
    if vacio3[i] == 'A':
        vacio2[i] = 1
    elif vacio3[i] == 'B':
        vacio2[i] = 1
    elif vacio3[i] == 'C':
        vacio2[i] = 2
    elif vacio3[i] ==  'D':
        vacio2[i] = 2
    elif vacio3[i] == 'E':
        vacio2[i] = 3

In [49]:
vacio2

array([2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 2,
       1, 1, 2, 1, 2, 1, 2, 1])

Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.

In [50]:
vacio2_final = vacio2.reshape(2,3,5)
vacio2_final

array([[[2, 2, 1, 1, 1],
        [1, 1, 1, 1, 2],
        [2, 2, 1, 2, 2]],

       [[1, 1, 2, 1, 1],
        [1, 2, 1, 1, 2],
        [1, 2, 1, 2, 1]]])