Ejercicio1º¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(1)
array1 = np.random.randint(1,5,(2,3))
array1

array([[2, 4, 1],
       [1, 4, 2]])

In [3]:
np.random.seed(1)
array2= np.random.randint(1,5,(2,3))
array2

array([[2, 4, 1],
       [1, 4, 2]])

Ejercicio2º Cread los siguientes arrays:
Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

In [4]:

array3 = np.round(np.random.uniform(0,10, size=(2,3,5)),0)
array3

array([[[ 3.,  1.,  1.,  2.,  3.],
        [ 4.,  5.,  4.,  7.,  2.],
        [ 9.,  0.,  7.,  4.,  6.]],

       [[ 1.,  2.,  8., 10.,  3.],
        [ 7.,  9.,  9.,  1.,  0.],
        [ 2.,  9.,  1.,  4., 10.]]])

In [5]:
unicos=np.unique(array3)
unicos

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus valores únicos y guarda los datos en una variable.

In [6]:
array4=np.random.binomial(10,0.3, size=(2,3,5))
array4

array([[[3, 4, 2, 4, 4],
        [0, 4, 6, 4, 2],
        [4, 1, 3, 5, 2]],

       [[2, 1, 0, 4, 2],
        [2, 3, 1, 3, 1],
        [3, 4, 1, 3, 4]]])

Ejercicio3º En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:
Elementos comunes entre los dos arrays

In [7]:
np.union1d(array3,array4)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Unión de los dos arrays

¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos
⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?

In [8]:
array3

array([[[ 3.,  1.,  1.,  2.,  3.],
        [ 4.,  5.,  4.,  7.,  2.],
        [ 9.,  0.,  7.,  4.,  6.]],

       [[ 1.,  2.,  8., 10.,  3.],
        [ 7.,  9.,  9.,  1.,  0.],
        [ 2.,  9.,  1.,  4., 10.]]])

In [9]:
array4

array([[[3, 4, 2, 4, 4],
        [0, 4, 6, 4, 2],
        [4, 1, 3, 5, 2]],

       [[2, 1, 0, 4, 2],
        [2, 3, 1, 3, 1],
        [3, 4, 1, 3, 4]]])

In [10]:
np.setdiff1d(array3, array4)

array([ 7.,  8.,  9., 10.])

coge los valores que tiene el primer array (array3) el orden en el que aparece la función importa, ya que si hubieramos puesto en primer lugar el array4 nos hubiera devuelto una lista distinta.

Ejercicioº4 Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.


In [11]:
array6= np.random.randint(1,100, size=80)
array6

array([ 4,  1, 78,  7, 53, 86, 71,  3, 77, 92, 22, 76,  8, 78, 73, 76, 77,
       44, 21, 31, 37,  8, 46, 69, 58, 83, 97, 14, 11, 24, 82,  8, 25, 75,
       93, 21, 33, 13, 66, 95, 61, 25, 83, 98,  3, 93, 99, 11, 55, 97, 83,
       87, 71, 67, 72, 49, 55, 16,  6, 18, 43, 21, 49, 23, 14, 98, 54, 85,
       11, 97, 56, 62, 57, 90, 22, 97, 84, 26, 15, 14])

In [12]:
array7=np.random.randint(1,100, size=80)
array7

array([85, 44,  7, 78, 57, 60, 16, 25, 10, 67, 72, 54, 70, 37, 22, 41, 78,
       92, 50, 48, 78, 41, 79, 46, 88, 17, 29, 46, 68, 67, 79, 47,  1, 30,
       64, 76, 36, 54, 94, 34,  3, 85, 84, 49, 55, 33, 29, 56, 83, 32, 29,
       95, 75,  9, 33,  9, 85, 78, 51, 80, 42, 65, 84, 25, 21, 45, 16, 31,
       92, 15, 20, 27, 87,  8, 54, 48, 61, 35, 33, 20])

Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2

In [13]:
array8 = np.unique(array6)
array8

array([ 1,  3,  4,  6,  7,  8, 11, 13, 14, 15, 16, 18, 21, 22, 23, 24, 25,
       26, 31, 33, 37, 43, 44, 46, 49, 53, 54, 55, 56, 57, 58, 61, 62, 66,
       67, 69, 71, 72, 73, 75, 76, 77, 78, 82, 83, 84, 85, 86, 87, 90, 92,
       93, 95, 97, 98, 99])

In [14]:
array9= np.unique(array7)
array9

array([ 1,  3,  7,  8,  9, 10, 15, 16, 17, 20, 21, 22, 25, 27, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 54,
       55, 56, 57, 60, 61, 64, 65, 67, 68, 70, 72, 75, 76, 78, 79, 80, 83,
       84, 85, 87, 88, 92, 94, 95])

Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

In [15]:
array10 = np.setdiff1d(array8,array9)
array10

array([ 4,  6, 11, 13, 14, 18, 23, 24, 26, 43, 53, 58, 62, 66, 69, 71, 73,
       77, 82, 86, 90, 93, 97, 98, 99])

Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

In [16]:
array11 = np.setdiff1d(array9,array8)
array11

array([ 9, 10, 17, 20, 27, 29, 30, 32, 34, 35, 36, 41, 42, 45, 47, 48, 50,
       51, 60, 64, 65, 68, 70, 79, 80, 88, 94])

Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

In [17]:
array12 = np.intersect1d(array8,array9)
array12

array([ 1,  3,  7,  8, 15, 16, 21, 22, 25, 31, 33, 37, 44, 46, 49, 54, 55,
       56, 57, 61, 67, 72, 75, 76, 78, 83, 84, 85, 87, 92, 95])

¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [18]:
array8.shape

(56,)

In [19]:
array9.shape

(58,)

In [20]:
array6.shape

(80,)

In [21]:
array7.shape

(80,)